/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author arman
 */
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class PainelDeEdicao extends javax.swing.JInternalFrame {

    /**
     * Creates new form PainelDeEdicao
     */
    public PainelDeEdicao() {
        initComponents();
    }

    private void fecha_Janela() {
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEdicao = new javax.swing.JPanel();
        lblTituloPainelEd = new javax.swing.JLabel();
        lblTituloEd = new javax.swing.JLabel();
        lblAnoProducaoEd = new javax.swing.JLabel();
        lblTempoProducaoEd = new javax.swing.JLabel();
        lblTempAnoProducaoEd = new javax.swing.JLabel();
        lblCategoriaEd = new javax.swing.JLabel();
        lblImagemEd = new javax.swing.JLabel();
        lblTituloPainel2Ed = new javax.swing.JLabel();
        lblNomeArtistaEd = new javax.swing.JLabel();
        lblResArtistaEd = new javax.swing.JLabel();
        lblTituloPainel3Ed = new javax.swing.JLabel();
        lblTipoProcedenciaEd = new javax.swing.JLabel();
        lblOrigemProcedenciaEd = new javax.swing.JLabel();
        txtTituloObraEd = new javax.swing.JTextField();
        txtResArtistaEd = new javax.swing.JTextField();
        txtNomeArtistaEd = new javax.swing.JTextField();
        txtOrigemProcedenciaEd = new javax.swing.JTextField();
        txtTempoAnoProducaoEd = new javax.swing.JTextField();
        txtSelectImagemEd = new javax.swing.JTextField();
        formatTxtAnoEd = new javax.swing.JFormattedTextField();
        cbCategoriaEd = new javax.swing.JComboBox<>();
        cbProcedenciaEd = new javax.swing.JComboBox<>();
        checkbInderteminadoEd = new javax.swing.JCheckBox();
        jBSelectImagemEd = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Obra de Arte");

        lblTituloPainelEd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTituloPainelEd.setText("Imformações da Obra");

        lblTituloEd.setText("Ttulo da obra:");

        lblAnoProducaoEd.setText("Ano de produção:");

        lblTempoProducaoEd.setText("Tempo de produção:");

        lblTempAnoProducaoEd.setText("Ano:");

        lblCategoriaEd.setText("Categoria:");

        lblImagemEd.setText("Imagem:");

        lblTituloPainel2Ed.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTituloPainel2Ed.setText("Imformações do Artista");

        lblNomeArtistaEd.setText("Nome do artista:");

        lblResArtistaEd.setText("Resistro do artista:");

        lblTituloPainel3Ed.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTituloPainel3Ed.setText("Imformações da Procedência");

        lblTipoProcedenciaEd.setText("Tipo de Procedência:");

        lblOrigemProcedenciaEd.setText("Origem da Procedência:");

        txtResArtistaEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResArtistaEdActionPerformed(evt);
            }
        });

        txtTempoAnoProducaoEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoAnoProducaoEdActionPerformed(evt);
            }
        });

        try {
            formatTxtAnoEd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cbCategoriaEd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Álbum", "Aquarela", "Colagem", "Desenho", "Escultura", "Foto", "Gravura", "Impressão", "Instalação", "Livro", "Múltiplo", "Objeto", "ObraDesinc", "Perform", "Pintura", "Relevo", "Tapeçaria", "Vídeo" }));

        cbProcedenciaEd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Aquisição", "Comodato", "Doação", "Espólio", "Legado", "Prêmio" }));

        checkbInderteminadoEd.setText("Indeterminado(caso não saiba)");

        jBSelectImagemEd.setText("Selecione imagem");
        jBSelectImagemEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSelectImagemEdActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Salvar");

        jToggleButton2.setText("Cancelar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEdicaoLayout = new javax.swing.GroupLayout(jPanelEdicao);
        jPanelEdicao.setLayout(jPanelEdicaoLayout);
        jPanelEdicaoLayout.setHorizontalGroup(
            jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEdicaoLayout.createSequentialGroup()
                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEdicaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloPainelEd)
                            .addComponent(lblTituloPainel2Ed)
                            .addGroup(jPanelEdicaoLayout.createSequentialGroup()
                                .addComponent(lblNomeArtistaEd)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomeArtistaEd, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEdicaoLayout.createSequentialGroup()
                                .addComponent(lblResArtistaEd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResArtistaEd, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTituloPainel3Ed)
                            .addGroup(jPanelEdicaoLayout.createSequentialGroup()
                                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoProcedenciaEd)
                                    .addComponent(lblOrigemProcedenciaEd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbProcedenciaEd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOrigemProcedenciaEd, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelEdicaoLayout.createSequentialGroup()
                                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelEdicaoLayout.createSequentialGroup()
                                        .addComponent(lblTempoProducaoEd)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTempAnoProducaoEd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTempoAnoProducaoEd, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelEdicaoLayout.createSequentialGroup()
                                        .addComponent(lblCategoriaEd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbCategoriaEd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)
                                .addComponent(checkbInderteminadoEd))
                            .addGroup(jPanelEdicaoLayout.createSequentialGroup()
                                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAnoProducaoEd)
                                    .addComponent(lblTituloEd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTituloObraEd, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formatTxtAnoEd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelEdicaoLayout.createSequentialGroup()
                                .addComponent(lblImagemEd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBSelectImagemEd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSelectImagemEd, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelEdicaoLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jToggleButton1)
                        .addGap(46, 46, 46)
                        .addComponent(jToggleButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEdicaoLayout.setVerticalGroup(
            jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEdicaoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTituloPainelEd)
                .addGap(26, 26, 26)
                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloEd)
                    .addComponent(txtTituloObraEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnoProducaoEd)
                    .addComponent(formatTxtAnoEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTempoProducaoEd)
                    .addComponent(lblTempAnoProducaoEd)
                    .addComponent(txtTempoAnoProducaoEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbInderteminadoEd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategoriaEd)
                    .addComponent(lblCategoriaEd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagemEd)
                    .addComponent(jBSelectImagemEd)
                    .addComponent(txtSelectImagemEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTituloPainel2Ed)
                .addGap(18, 18, 18)
                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeArtistaEd)
                    .addComponent(txtNomeArtistaEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResArtistaEd)
                    .addComponent(txtResArtistaEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lblTituloPainel3Ed)
                .addGap(18, 18, 18)
                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoProcedenciaEd)
                    .addComponent(cbProcedenciaEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigemProcedenciaEd)
                    .addComponent(txtOrigemProcedenciaEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtResArtistaEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResArtistaEdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResArtistaEdActionPerformed

    private void txtTempoAnoProducaoEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoAnoProducaoEdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoAnoProducaoEdActionPerformed

    private void jBSelectImagemEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSelectImagemEdActionPerformed
        //Abre o seletor de arquivos e  só mostra arquivos de imagem
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Procurar Imagem");
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagem", "jpg", "png");

        jfc.setFileFilter(filter);
        int retorno = jfc.showOpenDialog(null);

        //se apertar ABRIR pega a imagem e bota no campo de texto se for cancelar nada acontece
        if(retorno == JFileChooser.APPROVE_OPTION){
            File file = jfc.getSelectedFile();
            txtSelectImagemEd.setText(file.getPath());
        }

    }//GEN-LAST:event_jBSelectImagemEdActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
       fecha_Janela();
    }//GEN-LAST:event_jToggleButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCategoriaEd;
    private javax.swing.JComboBox<String> cbProcedenciaEd;
    private javax.swing.JCheckBox checkbInderteminadoEd;
    private javax.swing.JFormattedTextField formatTxtAnoEd;
    private javax.swing.JButton jBSelectImagemEd;
    private javax.swing.JPanel jPanelEdicao;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblAnoProducaoEd;
    private javax.swing.JLabel lblCategoriaEd;
    private javax.swing.JLabel lblImagemEd;
    private javax.swing.JLabel lblNomeArtistaEd;
    private javax.swing.JLabel lblOrigemProcedenciaEd;
    private javax.swing.JLabel lblResArtistaEd;
    private javax.swing.JLabel lblTempAnoProducaoEd;
    private javax.swing.JLabel lblTempoProducaoEd;
    private javax.swing.JLabel lblTipoProcedenciaEd;
    private javax.swing.JLabel lblTituloEd;
    private javax.swing.JLabel lblTituloPainel2Ed;
    private javax.swing.JLabel lblTituloPainel3Ed;
    private javax.swing.JLabel lblTituloPainelEd;
    private javax.swing.JTextField txtNomeArtistaEd;
    private javax.swing.JTextField txtOrigemProcedenciaEd;
    private javax.swing.JTextField txtResArtistaEd;
    private javax.swing.JTextField txtSelectImagemEd;
    private javax.swing.JTextField txtTempoAnoProducaoEd;
    private javax.swing.JTextField txtTituloObraEd;
    // End of variables declaration//GEN-END:variables
}
