package telas;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import estruturas.Arte;
import estruturas.Persistencia;
import javax.swing.JOptionPane;

/** Painel de Cadastro de Obras de Artes
 *    descrição:
 *      Esse painel possuí tudo acerca do cadastro de uma obra de arte
 *      efetuado no acervo do museu.
 * 
 *    @author Grupo 06
 *      alunos: Armando Neto, Douglas Lima
 *              Drayton Corrêa, Ewerton Santos
 */

public class PainelDeCadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form PainelDeCadastro
     */
    public PainelDeCadastro() {
        initComponents();
    }
    
    /** Método que Retorna um Objeto do tipo Arte
     *    Descrição:
     *      O método pega todos os dados registrados pelo usuário nos campos
     *      dispostos para tal.
     */
    private Arte Retorna_Arte(){    
        try {
            return new Arte(String.valueOf(txtTituloObra.getText())        , String.valueOf(txtNomeArtista.getText())       ,
                            String.valueOf(txtResArtista.getText())        , Integer.parseInt(formatTxtAno.getText())       ,
                            String.valueOf(cbCategoria.getSelectedItem())  , Integer.parseInt(txtTempoAnoProducao.getText()), 
                            String.valueOf(cbProcedencia.getSelectedItem()), String.valueOf(txtOrigemProcedencia.getText()));
            
        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(rootPane, "Valores Ivalidos", "Aviso", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    /** Método que Fecha a Janela Aberta
     *    Descrição:
     *      O método simplesmente fecha por completo a janela aberta no momento
     *      em que ele é chamado.
     */
    private void fecha_Janela() {
        this.dispose();
    }
    
    private boolean existeNaLista(int tomb) {
        for (Arte a : p.getCad()) {
            if (a.getTombo() == tomb) {
                return true;
           }
        }
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanelCadastro = new javax.swing.JPanel();
        lblTituloPainel = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblAnoProducao = new javax.swing.JLabel();
        lblTempoProducao = new javax.swing.JLabel();
        lblTempAnoProducao = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        lblTituloPainel2 = new javax.swing.JLabel();
        lblNomeArtista = new javax.swing.JLabel();
        lblResArtista = new javax.swing.JLabel();
        lblTituloPainel3 = new javax.swing.JLabel();
        lblTipoProcedencia = new javax.swing.JLabel();
        lblOrigemProcedencia = new javax.swing.JLabel();
        txtTituloObra = new javax.swing.JTextField();
        txtResArtista = new javax.swing.JTextField();
        txtNomeArtista = new javax.swing.JTextField();
        txtOrigemProcedencia = new javax.swing.JTextField();
        txtTempoAnoProducao = new javax.swing.JTextField();
        txtSelectImagem = new javax.swing.JTextField();
        formatTxtAno = new javax.swing.JFormattedTextField();
        cbCategoria = new javax.swing.JComboBox<>();
        cbProcedencia = new javax.swing.JComboBox<>();
        checkbInderteminado = new javax.swing.JCheckBox();
        jBSelectImagem = new javax.swing.JButton();
        jBCancelarCadastro = new javax.swing.JButton();
        jBSalvarCadastro = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastrar Obra de Arte ");

        lblTituloPainel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTituloPainel.setText("Imformações da Obra");

        lblTitulo.setText("Ttulo da obra:");

        lblAnoProducao.setText("Ano de produção:");

        lblTempoProducao.setText("Tempo de produção:");

        lblTempAnoProducao.setText("Ano:");

        lblCategoria.setText("Categoria:");

        lblImagem.setText("Imagem:");

        lblTituloPainel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTituloPainel2.setText("Imformações do Artista");

        lblNomeArtista.setText("Nome do artista:");

        lblResArtista.setText("Resistro do artista:");

        lblTituloPainel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTituloPainel3.setText("Imformações da Procedência");

        lblTipoProcedencia.setText("Tipo de Procedência:");

        lblOrigemProcedencia.setText("Origem da Procedência:");

        txtResArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResArtistaActionPerformed(evt);
            }
        });

        txtTempoAnoProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoAnoProducaoActionPerformed(evt);
            }
        });

        try {
            formatTxtAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Álbum", "Aquarela", "Colagem", "Desenho", "Escultura", "Foto", "Gravura", "Impressão", "Instalação", "Livro", "Múltiplo", "Objeto", "ObraDesinc", "Perform", "Pintura", "Relevo", "Tapeçaria", "Vídeo" }));

        cbProcedencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Aquisição", "Comodato", "Doação", "Espólio", "Legado", "Prêmio" }));

        checkbInderteminado.setText("Indeterminado (Caso não saiba)");
        checkbInderteminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbInderteminadoActionPerformed(evt);
            }
        });

        jBSelectImagem.setText("Selecionar Imagem");
        jBSelectImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSelectImagemActionPerformed(evt);
            }
        });

        jBCancelarCadastro.setText("Cancelar");
        jBCancelarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarCadastroActionPerformed(evt);
            }
        });

        jBSalvarCadastro.setText("Salvar");
        jBSalvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblTempoProducao)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCancelarCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBSalvarCadastro))
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTempAnoProducao)
                                    .addComponent(lblAnoProducao)
                                    .addComponent(lblTitulo)
                                    .addComponent(lblImagem)
                                    .addComponent(lblCategoria))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTituloObra, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLayout.createSequentialGroup()
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(formatTxtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtTempoAnoProducao, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jBSelectImagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSelectImagem)
                                            .addComponent(checkbInderteminado, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))))
                            .addComponent(lblTituloPainel2)
                            .addComponent(lblTituloPainel3)
                            .addComponent(lblTituloPainel)))
                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelCadastroLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(lblOrigemProcedencia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtOrigemProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCadastroLayout.createSequentialGroup()
                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(lblTipoProcedencia))
                                .addComponent(lblResArtista, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblNomeArtista, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtResArtista, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbProcedencia, javax.swing.GroupLayout.Alignment.LEADING, 0, 141, Short.MAX_VALUE))
                                .addComponent(txtNomeArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPainel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatTxtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnoProducao))
                .addGap(5, 5, 5)
                .addComponent(lblTempoProducao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTempoAnoProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbInderteminado)
                    .addComponent(lblTempAnoProducao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagem)
                    .addComponent(jBSelectImagem)
                    .addComponent(txtSelectImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategoria)
                    .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lblTituloPainel2)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeArtista)
                    .addComponent(txtNomeArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResArtista)
                    .addComponent(txtResArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lblTituloPainel3)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoProcedencia)
                    .addComponent(cbProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigemProcedencia)
                    .addComponent(txtOrigemProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelarCadastro)
                    .addComponent(jBSalvarCadastro))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtResArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResArtistaActionPerformed

    private void txtTempoAnoProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoAnoProducaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoAnoProducaoActionPerformed
    
    /** Botão de Selecionar Imagem
     *    Descrição:
     *     Abre a janela de pesquisa para a busca da imagem que será salva
     *     junto aos demais dados da obra de arte.
     */
    private void jBSelectImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSelectImagemActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Procurar Imagem");
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagem", "jpg", "png");
                
        jfc.setFileFilter(filter);        
        int retorno = jfc.showOpenDialog(null);
        
        /*
        * Consequências:
        *  Se apertar em ABRIR: pega a imagem e bota no campo de texto.
        *  Se apertar em CANCELAR: nada irá acontecer.
        */
        
        if(retorno == JFileChooser.APPROVE_OPTION){
            File file = jfc.getSelectedFile();
            txtSelectImagem.setText(file.getPath());
        }


    }//GEN-LAST:event_jBSelectImagemActionPerformed

    /** Botão de Cancelar
     *    Descrição:
     *     Ao apertar o botão o procedimento será cancelado.
     */
    private void jBCancelarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarCadastroActionPerformed
        fecha_Janela();
    }//GEN-LAST:event_jBCancelarCadastroActionPerformed
    
    /** Botão de Salvar
     *    Descrição:
     *     Ao apertar o botão o objeto será salvo no arquivo.
     */
    private void jBSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarCadastroActionPerformed
        if (null != Retorna_Arte()) {
            Arte a = Retorna_Arte();
            System.out.println(a.toString());
            if (!existeNaLista(a.getTombo())) {
                p.getCad().add(a);
                p.setupGravar();
                p.addRecords(p.getCad()); // Adciona um produto a lista.
                p.cleanupGravar();        // Fecha o arquivo           
                
                fecha_Janela();
                
                JOptionPane.showMessageDialog(rootPane, "Produto Cadastrado com Sucesso");
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Código de Produto já Cadastrado.", "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Produto não Cadastrado!", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBSalvarCadastroActionPerformed

    private void checkbInderteminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbInderteminadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkbInderteminadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbProcedencia;
    private javax.swing.JCheckBox checkbInderteminado;
    private javax.swing.JFormattedTextField formatTxtAno;
    private javax.swing.JButton jBCancelarCadastro;
    private javax.swing.JButton jBSalvarCadastro;
    private javax.swing.JButton jBSelectImagem;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblAnoProducao;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNomeArtista;
    private javax.swing.JLabel lblOrigemProcedencia;
    private javax.swing.JLabel lblResArtista;
    private javax.swing.JLabel lblTempAnoProducao;
    private javax.swing.JLabel lblTempoProducao;
    private javax.swing.JLabel lblTipoProcedencia;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloPainel;
    private javax.swing.JLabel lblTituloPainel2;
    private javax.swing.JLabel lblTituloPainel3;
    private javax.swing.JTextField txtNomeArtista;
    private javax.swing.JTextField txtOrigemProcedencia;
    private javax.swing.JTextField txtResArtista;
    private javax.swing.JTextField txtSelectImagem;
    private javax.swing.JTextField txtTempoAnoProducao;
    private javax.swing.JTextField txtTituloObra;
    // End of variables declaration//GEN-END:variables
  
    private static Persistencia p = new Persistencia();
}
