package telas;

import estruturas.Persistencia;
import estruturas.Arte;
import estruturas.ManipulaçãoDeImagem;
import java.awt.Dimension;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static telas.PainelPrincipal.jTelaPrincipal;

/** Painel de Amostra das Obras de Arte
 *    Descrição:
 *      Esse painel exibe todos os dados de uma obra de arte para a
 *      visualização, mas não para serem editados.
 * 
 *    @author Grupo 06
 *      Alunos: Armando Neto, Douglas Lima
 *              Drayton Corrêa, Ewerton Santos
 */

public class PainelDeAmostra extends javax.swing.JInternalFrame {
     /** Construtor:
      *    Descrição:
      *      Recebe como parametro um inteiro que é o Tombo da Arte o qual foi
      *      selecionada no PainelDePesquisa. Após isso, abre e lê a lista, 
      *      salva na variavel cad e pega o metodo de mostraArte para exibir 
      *      os detalhes no momento em que abrir o painel.
      */
    public PainelDeAmostra(int tombo) {
        p.setupLer();
        if (p.getContinua() == true) {
            p.readRecords();
            p.cleanupLer();
            cad = p.getCad();
        }
        this.tombo = tombo;
        initComponents();
        MostraArte(tombo);
    }
    
   //MÉTODOS:
     /** Método que Fecha a Janela Aberta
       *    Descrição:
       *      O método simplesmente fecha por completo a janela aberta no momento
       *      em que ele é chamado.
       */
    private void fecha_Janela() {
        this.dispose();
    }

     /** Método que Centraliza a Janela 
      *    Descrição: 
      *      O método faz com que as janelas sejam abertas no centro da tela.
      */
    public void setPosicao() {
        Dimension d = jTelaPrincipal.getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

     /** Método que Pega os Dados de uma Obra Registrada
      *      Descrição:
      *        Pega como parâmetro o Tombo que foi recebido na abertura da 
      *        classe, comparada com o tombo de cada objeto Arte na lista
      *        e quando encontra um igual mostra os detalhes dele.  
      */
    private void MostraArte(int tombo) {
        for (Arte a : cad) {
            if (a.getTombo() == tombo) {
                lblMostraTitulo.setText(a.getTitulo());
                lblMostraAno.setText(String.valueOf(a.getAno()));
                lblMostraTempProducao.setText(a.getPeriodoProducao());
                lblMostraCategoria.setText(a.getCategoria());
                lblMostraNomeArtista.setText(a.getNome());
                lblMostraRegiArtista.setText(String.valueOf(a.getRegistro()));
                lblMostraTipoProce.setText(a.getProcedencia());
                lblMostraOrigemProce.setText(a.getOrigem());
                lblMostraTombo.setText(String.valueOf(a.getTombo()));
                ManipulaçãoDeImagem.exibiImagemLabel(a.getImagem(), labelImagem);
            }
        }

    }

     /** Método que Verifica se o Tombo já foi Cadastrado
      *    Descrição:
      *      Essse método auxilia no momemento em que for pesquisado
      *      uma obra pelo número de tombo para edita-la. Ele vai 
      *      desempenhar o papel de verificar se o número de tombo desejado 
      *      já foi atribuito para algum objeto
      */
    private boolean existeNaLista(int tomb) {
        for (Arte a : cad) {
            if (a.getTombo() == tomb) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelImagem = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JLabel11 = new javax.swing.JLabel();
        botaoFechar = new javax.swing.JToggleButton();
        botaoEditar = new javax.swing.JToggleButton();
        lblMostraTitulo = new javax.swing.JLabel();
        lblMostraAno = new javax.swing.JLabel();
        lblMostraTempProducao = new javax.swing.JLabel();
        lblMostraCategoria = new javax.swing.JLabel();
        lblMostraNomeArtista = new javax.swing.JLabel();
        lblMostraRegiArtista = new javax.swing.JLabel();
        lblMostraTipoProce = new javax.swing.JLabel();
        lblMostraOrigemProce = new javax.swing.JLabel();
        lblMostraTombo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Item Selecionado");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Categoria:");

        jLabel5.setText("Nome do Artista:");

        jLabel6.setText("Registro do Artista:");

        jLabel7.setText("Tipo de Procedência:");

        jLabel1.setText("Título da Obra:");

        jLabel2.setText("Ano de Produção:");

        jLabel8.setText("Origem da Procedência:");

        jLabel3.setText("Tempo de Produção(anos):");

        JLabel11.setText("Número de Tombo:");

        botaoFechar.setText("Fechar");
        botaoFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblMostraCategoria))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblMostraNomeArtista))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblMostraTitulo))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblMostraAno))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblMostraRegiArtista))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblMostraTipoProce))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblMostraTempProducao))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblMostraOrigemProce))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(JLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblMostraTombo))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoEditar)
                            .addGap(18, 18, 18)
                            .addComponent(botaoFechar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(labelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblMostraTitulo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblMostraAno))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblMostraTempProducao))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblMostraCategoria))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblMostraNomeArtista))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblMostraRegiArtista))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblMostraTipoProce))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblMostraOrigemProce))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel11)
                    .addComponent(lblMostraTombo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoFechar)
                    .addComponent(botaoEditar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   //BOTÕES:
     /** Botão de Editar
      *    Descrição:
      *      Se o botão for pressionado, é feita uma varredura em todos os
      *      registros cadastrados em busca de um número de tombo igual
      *      com o mostrado na tela de amostra atual. Quando ele é encontrado 
      *      abre-se um painel de registro com os dados salvos daquela obra.
      */
    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        boolean errado = true;
        while (errado) {
            if (errado == true) {
                try {
                    int tomboEdit;
                    tomboEdit = tombo;
                    if (existeNaLista(tomboEdit)) {
                        PainelDeRegistro painelE = new PainelDeRegistro(tomboEdit);
                        painelE.setTitle("Editar Obra de Arte");
                        jTelaPrincipal.add(painelE);
                        painelE.setPosicao();
                        painelE.setVisible(true);
                        break;
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Tombo não Encontrado.", "Aviso", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                } catch (NumberFormatException n) {
                    JOptionPane.showMessageDialog(rootPane, "Caractere digitado Inválido.", "Aviso", JOptionPane.ERROR_MESSAGE);
                }
                errado = false;
            }
        }
        this.dispose();
    }//GEN-LAST:event_botaoEditarActionPerformed

     /** Botão de Fechar
      *    Descrição:
      *      Ao ser pressionado, fecha o painel de amostra.
      */
    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        fecha_Janela();        // TODO add your handling code here:
    }//GEN-LAST:event_botaoFecharActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel11;
    private javax.swing.JToggleButton botaoEditar;
    private javax.swing.JToggleButton botaoFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JLabel lblMostraAno;
    private javax.swing.JLabel lblMostraCategoria;
    private javax.swing.JLabel lblMostraNomeArtista;
    private javax.swing.JLabel lblMostraOrigemProce;
    private javax.swing.JLabel lblMostraRegiArtista;
    private javax.swing.JLabel lblMostraTempProducao;
    private javax.swing.JLabel lblMostraTipoProce;
    private javax.swing.JLabel lblMostraTitulo;
    private javax.swing.JLabel lblMostraTombo;
    // End of variables declaration//GEN-END:variables
    //Outros Atributos:
    private static Persistencia p = new Persistencia();
    private int tombo;
    private LinkedList<Arte> cad = new LinkedList<Arte>();
    //Fim dos outros Atributos;
}
